# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deploy and Test

on:
  push:
    branches: ["fly-deploy"]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app
        run: flyctl deploy --remote-only -a whereis-api-v0
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PROD }}

  test:
    name: Run Deno tests
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run linter
        run: deno lint

      - name: Run type check
        run: deno check .

      - name: Set env vars for main branch
        if: github.ref_name == 'fly-deploy'
        run: |
          echo "WHEREIS_API_URL=https://whereis-api-v0.fly.dev" >> $GITHUB_ENV

      - name: Run tests
        env:
          FDX_CLIENT_ID: ${{ secrets.FDX_CLIENT_ID }}
          FDX_CLIENT_SECRET: ${{ secrets.FDX_CLIENT_SECRET }}
          SFEX_PARTNER_ID: ${{ secrets.SFEX_PARTNER_ID }}
          SFEX_CHECK_WORD: ${{ secrets.SFEX_CHECK_WORD }}
          WHEREIS_API_KEY: ${{ secrets.WHEREIS_API_KEY }}
        run: deno test -A tests/main-test.ts
